services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128m
          cpus: "0.5"
        reservations:
          memory: 64m
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
